[package]
name = "htu-net-login"
version = "0.1.2"
edition = "2021"

[dependencies]
tokio = { version = "*", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
htu-net-login-daemon = { path = "../daemon", optional = true }
htu-net-login-tui = { path = "../tui", optional = true }
clap = { version = "*", features = ["derive"] }
anyhow = { version = "*" }
dirs = { version = "*" }
runas = { version = "*"}
flexi_logger = { version = "*" }
log = { version = "*" }
reqwest = { version = "*"}

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["winbase", "winnt", "processthreadsapi", "securitybaseapi"] }
winreg = { version = "*" }

[features]
default = ["release"]
release = ["daemon", "tui"]
tui = ["htu-net-login-tui"]
daemon = ["htu-net-login-daemon"]